In [2]:
%load_ext google.cloud.bigquery
%matplotlib inline
from google.cloud import bigquery
client = bigquery.Client()
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests

In [2]:
def create_sql(database, table):
    return '''
            SELECT
                *
            FROM `{}.{}`
            LIMIT 15
            '''.format(database, table)

### transactions

In [95]:
database = 'bigquery-public-data.ethereum_blockchain'
table = 'transactions'
sql = create_sql(database, table)

df = client.query(sql).to_dataframe()
df.head()['hash'][0]

'0x1d023549fae00a06c5aa993846894c31f6278f8941890d606ac68634aac032f0'

### cell magic

In [93]:
%%bigquery txns
SELECT
    *
FROM `bigquery-public-data.ethereum_blockchain.transactions`
WHERE to_address IS NULL
LIMIT 15

,hash,nonce,transaction_index,from_address,to_address,value,gas,gas_price,input,receipt_cumulative_gas_used,receipt_gas_used,receipt_contract_address,receipt_root,receipt_status,block_timestamp,block_number,block_hash
0,0xe6b02f41e5b4438a987f908bb919eca274807c5d823a...,105,1,0x0e95adb39a2dfe1c8f3969de4480a5d3ddfadebd,None,0,800000,20000000000,0x606060405260008054600160a060020a031916331790...,313670,292670,0x54676cd2f1e8d296e7ac69f69675f936c4629dde,0x2c624ed478d2a0efb53b4494260746794465784820d2...,None,2016-12-11 03:41:34+00:00,2786327,0x90938f89f452d204b7477310e9797989d1e724d0e3c3...
1,0x4543c1eca44543e0232a296d0b7ebbbbfe990f99d4b9...,95,1,0x0e95adb39a2dfe1c8f3969de4480a5d3ddfadebd,None,0,800000,20000000000,0x606060405260008054600160a060020a031916331790...,263359,242359,0x04f0c372cdce16924ecbcc443c38ce996dce2202,0x74b5fa3b2dc03d17985d845c585769dbeb857057e9bb...,None,2016-12-11 00:16:59+00:00,2785477,0x97df6b6d30aa33919cf953a7e5a6081bba49a409bdba...
2,0xe25feed0854871e21b8b8f532ac823fe076d8b2c354a...,99,8,0x0e95adb39a2dfe1c8f3969de4480a5d3ddfadebd,None,0,800000,20000000000,0x606060405260008054600160a060020a031916331790...,513018,278360,0x5df775f6b6cb6ad2b7e863dc5c4bf66c18d63416,0xf0937882900b07958b5d61864e3d733f208b1056b436...,None,2016-12-11 03:04:55+00:00,2786163,0x4eea302adbfb7c8bc2acd098789ce78c5fc23d5f6637...
3,0x404ebdda8b5a98d61f2000fa3b92069c1a041486d00c...,101,6,0x0e95adb39a2dfe1c8f3969de4480a5d3ddfadebd,None,0,800000,20000000000,0x606060405260008054600160a060020a031916331790...,424706,298706,0xe0885628cba5d0d7db55e670a9f2e24a93eaa6ac,0x8029bc58aa2f7e6e602a71bc2cc0989637601c882bde...,None,2016-12-11 03:09:40+00:00,2786191,0xc4289912fe0d939f61bddbc36bf693b6f8877ef5508c...
4,0x362395b284d7e46ca6d5b5dcb7e671d4010c23d28fc4...,5,8,0x00ea6e2e39329489b7b2c3e9d1fd62f747f809bc,None,0,800000,20000000000,0x6060604052600261010860005055604051611c453803...,1695534,800000,0x6150cbd111be39e382f969c89c07ae4f200814a2,0xcede9ee0005dc2ec1e83373e1163d5161281e70702ea...,None,2016-12-11 05:59:00+00:00,2786909,0x011cee027cde26992ecd26fd01eba65f786c41de5122...
5,0x9c771607799845544b762f03237a10978613a4333c93...,9,16,0x00ea6e2e39329489b7b2c3e9d1fd62f747f809bc,None,0,1600000,20000000000,0x6060604052600261010860005055604051611c453803...,3315000,1600000,0x64dd210c3b1bf7f8a1dcefcbb06d81b603b2e8e5,0x54a2b2ae715d0d68af693555a03030d1aa67a4f73b85...,None,2016-12-11 05:59:41+00:00,2786912,0xb3de757ab834ca70507d3b159da8f8a32a43e4a7af9a...
6,0xe8cd214a11f7015d0c60414b76c680e3f22c86ea3e33...,92,8,0x0e95adb39a2dfe1c8f3969de4480a5d3ddfadebd,None,0,800000,20000000000,0x606060405260008054600160a060020a031916331790...,511586,264774,0xee939dbde9dec924bbe18c59ea8883d2e87d2332,0xd13d1ecc6a7f8ceefb32b411faf13d0ea1ae58687404...,None,2016-12-11 00:06:13+00:00,2785428,0x9ebe32354a6c5c1317b28403baab0712e28dbd7f79b9...
7,0xb8f228a45a680a72fd6baf6fc43ef52a0a024e8ac6c8...,5490,8,0xe9eeaec75883f0e389a78e2260bfac1776df2f1d,None,0,650000,20000000000,0x606060408181526001805460a060020a60ff02191690...,1970326,297169,0x70747726fd79cf73fb3055d5350f9248379081ad,0x15231e821cd1955560b33ed7d1edc2bf76ac9e7e5213...,None,2016-12-11 10:50:03+00:00,2788166,0x3c39cac96600f0c0bf0cdb9196d85c99a10c6cffe7dc...
8,0x2ec0ed35fe2d7d77a19a3b0882f15d36a919b96c8474...,5502,14,0xe9eeaec75883f0e389a78e2260bfac1776df2f1d,None,0,650000,20000000000,0x606060408181526001805460a060020a60ff02191690...,2448687,297169,0x885a665b654ed42e0a846169267e3eb547406b6d,0xbc7af7ee4011d762179114e94d2d09e48ab4fb5c20dd...,None,2016-12-11 10:50:32+00:00,2788169,0x83f57327e1adff751baa2bd3973580129513403dff0b...
9,0xcfc0502ba22b968664ebd404543d40a24ed538d07ab6...,5462,9,0xe9eeaec75883f0e389a78e2260bfac1776df2f1d,None,0,650000,20000000000,0x606060408181526001805460a060020a60ff02191690...,2064629,297169,0x6d628169dd66be184e5fc21abf3c36befee2e546,0x82b85bf241e36ec51c4aba866717c4ef3d72910008db...,None,2016-12-11 04:56:17+00:00,2786644,0xf3f3a998bb7288622fa1cdfb043aa68e417af21683d3...
10,0xa81def96f92aa482aebc5c7b4e4281ced7237a0be1d7...,5476,21,0xe9eeaec75883f0e389a78e2260bfac1776df2f1d,None,0,650000,20000000000,0x606060408181526001805460a060020a60ff02191690...,2305441,297169,0x9da1cb2c9683be164cbc045f59c1b3788e7c9231,0xa9ea003b6040539b30035475e0c92beff093396aa294...,None,2016-12-11 05:03:45+00:00,2786677,0xe8406215154ecc65a6cfb782aa4f93165da602ba2bcd...
11,0xae62599eb8847f37da7d784b7f9986260279f68ebf6e...,5491,9,0xe9eeaec75883f0e389a78e2260bfac1776df2f1d,None,0,350000,20000000000,0x606060408181526001805460a060020a60ff02191690...,2267559,297233,0x441f5256ec2ae8d4105e2f45c485b882790ba88d,0xa29c07f3e503cfc285298ea4b631011459e86d9ed342...,None,2016-12-11 10:50:03+00:00,2788166,0x3c39cac96600f0c0bf0cdb9196d85c99a10c6cffe7dc...
12,0xa469e2fa9a97e8f25ea1d7c6633d800195d1570b14d7...,5503,15,0xe9eeaec75883f0e389a78e2260bfac1776df2f1d,None,0,350000,20000000000,0x606060408181526001805460a060020a60ff02191690...,2745920,297233,0x8e5541f623c7001e697c99ca2c4019f06885c459,0xb21ad80296cd5d5571ecb143c083d24e2db283035ffa...,None,2016-12-11 10:50:32+00:00,2788169,0x83f57327e1adff751baa2bd3973580129513403dff0b...
13,0x2ff7d12e84004265806acd0fa21708ae5a11da36de93...,3,6,0x00111a933b91da91eed494c5c0a9bb9fb2fbeadc,None,0,220690,20000000000,0x606060405234610000575b30600060006101000a8154...,475695,183908,0xc21a60e2b976d9e16f1d8b71d9fd97bb7249a09c,0x5ae5ad67b13323a45658f8d459545cec4531670f20b8...,None,2016-12-11 13:14:24+00:00,2788775,0xccc4242e22ae558043df83c78d11a9c5dc6eadab0c76...
14,0x424a3d37facbea9b3538f94cbfaf1d8786ac87c24fa5...,3,2,0x866e3f722e9bc23e3cf1d35f1564c35159bc9186,None,0,1300000,20000000000,0x6060604052346100005760405161063e38038061063e...,678747,636747,0x5d4798ff2722e856fd753478c4d9010939d869b5,0x889f7d8fd7b81e76aafc89abc33a1fdf49dd2e5d3055...,None,2016-12-11 15:51:35+00:00,2789464,0x0a90d0204f2e412466f341b41ca011f586e8c0adec11...

In [123]:
database = 'bigquery-public-data.ethereum_blockchain'
table = 'blocks'
sql = create_sql(database, table)

df = client.query(sql).to_dataframe()

Creating a new dataset on Google Cloud to store toy data

In [136]:
dataset_id='transactions_subset'
dataset = client.create_dataset(dataset_id)

In [137]:
TABLE = 'subset'
job_config = bigquery.QueryJobConfig()
# Set the destination table
table_ref = client.dataset(dataset_id).table(TABLE)
job_config.destination = table_ref

sql = """
    SELECT *
    FROM `bigquery-public-data.ethereum_blockchain.transactions`
    ORDER BY block_timestamp DESC
    LIMIT 20000;
"""

# Start the query, passing in the extra configuration.
query_job = client.query(
    sql,
    # Location must match that of the dataset(s) referenced in the query
    # and of the destination table.
    location='US',
    job_config=job_config)  # API request - starts the query

query_job.result()  # Waits for the query to finish
print('Query results loaded to table {}'.format(table_ref.path))

Query results loaded to table /projects/eth-tokens/datasets/transactions_subset/tables/subset

subset transactions table to manageable number of rows: 20,000? Trying with most recent

In [6]:
%%bigquery
WITH tot AS
    (WITH subset AS(SELECT *
                FROM `bigquery-public-data.ethereum_blockchain.transactions`
                ORDER BY block_timestamp DESC
                LIMIT 20000
                   ),

    f AS(SELECT DISTINCT from_address, count(*) as num_outgoing_txns
        FROM subset
        GROUP BY from_address),
    t AS(SELECT DISTINCT to_address, count(*) as num_incoming_txns
        FROM subset
        GROUP BY to_address)
    SELECT COALESCE(from_address,to_address) as addr,
            COALESCE(num_outgoing_txns,0) as outgoing_txns,
            COALESCE(num_incoming_txns,0) as incoming_txns
    FROM f FULL JOIN t
    ON f.from_address = t.to_address)

SELECT *, (outgoing_txns + incoming_txns) as total_txns
FROM tot
ORDER BY total_txns desc
LIMIT 50

,addr,outgoing_txns,incoming_txns,total_txns
0,0xea674fdde714fd979de3edf0f56aa9716b898ec8,1628,0,1628
1,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,804,0,804
2,0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208,0,460,460
3,0x5892aad75a615014aa88c4b621caff1fe45dc850,0,387,387
4,0xa7a7899d944fe658c4b0a1803bab2f490bd3849e,373,0,373
5,0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be,89,252,341
6,0xe8780b48bdb05f928697a5e8155f672ed91462f7,0,295,295
7,0xad3ee1abb108e0a18b43b41632a23b64e9121ac3,278,0,278
8,0x29d31eb86dd7cabb2d00f6a62eecfa1cf6e33135,0,276,276
9,0x1a7a8bd9106f2b8d977e08582dc7d24c723ab0db,0,275,275
10,0xd7b9a9b2f665849c4071ad5af77d8c76aa30fb32,0,264,264
11,0xdd7d1f1ce4eb1d83ee5f217160cad890bdba0c86,258,0,258
12,0x0fb843d37aa2a99db8d81af9fe2f0a6485c7c002,0,258,258
13,0x06012c8cf97bead5deae237070f9587f8e7a266d,0,256,256
14,0x6cace0528324a8afc2b157ceba3cdd2a27c4e21f,241,0,241
15,0xa3c1e324ca1ce40db73ed6026c4a177f099b5770,0,241,241
16,0x6090a6e47849629b7245dfa1ca21d94cd15878ef,0,236,236
17,0x00ab424d2019bc0f4c648232c6e7d181a34034b8,225,0,225
18,0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98,224,0,224
19,0x8d12a197cb00d4747a1fe03395095ce2a5cc6819,0,222,222
20,0xdcbb8122400735667d0a03f088b5bd4377e0b5f2,214,0,214
21,0x503f9794d6a6bb0df8fbb19a2b3e2aeab35339ad,0,214,214
22,0xe5f166c0d8872b68790061317bb6cca04582c912,0,211,211
23,0x4f39f9fd43644156deeb90854b19f866f60fab66,208,0,208
24,0xa62142888aba8370742be823c1782d17a0389da1,0,208,208
25,0xd1ceeeeee83f8bcf3bedad437202b6154e9f5405,0,195,195
26,0x876eabf441b2ee5b5b0554fd502a8e0600950cfa,158,12,170
27,0x1ce7ae555139c5ef5a57cc8d814a867ee6ee33d8,0,167,167
28,0xaa86bb5ce320e7e425af0caf988f2c3a5e0b8338,0,164,164
29,0x7b45a572ea991887a01fd919c05edf1cac79c311,0,163,163
30,0x02814c0b5ed1038bd03c55e8949b6de0338ee81e,155,0,155
31,0x5dcaa1d8d8132e5bf9cf12deccfc0cecf26a780d,131,22,153
32,0x457804851eaf090dad4871f9609010c6868d99d4,147,0,147
33,0xf5bec430576ff1b82e44ddb5a1c93f6f9d0884f3,11,129,140
34,0x5baeac0a0417a05733884852aa068b706967e790,10,121,131
35,0x44e44897fc076bc46aae6b06b917d0dfd8b2dae9,119,0,119
36,0x83e2be8d114f9661221384b3a50d24b96a5653f5,0,119,119
37,0x45fe887bb6ebd0a8bb8c450456191d18114adf99,0,113,113
38,0x000000b6e4fec2ab4fa3ec2af763248c17973612,0,111,111
39,0xba826fec90cefdf6706858e5fbafcb27a290fbe0,111,0,111
40,0x4ee1d2adbc73b90fc7b557051b730ca0ad98ab83,0,107,107
41,0x827727b4c3f75ea6eb6bd2cc256de40db2b13665,0,104,104
42,0x00000000c0293c8ca34dac9bcc0f953532d34e4d,99,0,99
43,0xb2930b35844a230f00e51431acae96fe543a0347,89,1,90
44,0xa52e014b3f5cc48287c2d483a3e026c32cc76e6d,0,89,89
45,0x1290593928376d834b70585ca12bcf6f6de10ac9,89,0,89
46,0x91c82b9e9e85a5eee5ea5815148d118c6a11d091,89,0,89
47,0xe9989066dc9799412ec14416accf62753275205e,0,89,89
48,0xa10ddd53f3da20cb9ce3c91e0ac8790a838bdb3d,47,40,87
49,0x6938298963357122f72592add77109767c7d67f0,86,0,86

need to default to zero when no transactions are present

In [4]:
%%bigquery
SELECT from_address, nonce 
FROM `bigquery-public-data.ethereum_blockchain.transactions`
WHERE from_address = '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
ORDER BY nonce desc
LIMIT 5

                                 from_address     nonce
0  0xea674fdde714fd979de3edf0f56aa9716b898ec8  16425925
1  0xea674fdde714fd979de3edf0f56aa9716b898ec8  16425924
2  0xea674fdde714fd979de3edf0f56aa9716b898ec8  16425923
3  0xea674fdde714fd979de3edf0f56aa9716b898ec8  16425922
4  0xea674fdde714fd979de3edf0f56aa9716b898ec8  16425921

In [ ]:
%%bigquery
SELECT from_address, nonce 
FROM `bigquery-public-data.ethereum_blockchain.transactions`
WHERE from_address = '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
ORDER BY nonce desc
LIMIT 5

In [7]:
%%bigquery
WITH tot AS
    (WITH subset AS(SELECT *
                FROM `bigquery-public-data.ethereum_blockchain.transactions`
                   ),

    f AS(SELECT DISTINCT from_address, max(nonce) as maxnonce, count(*) as num_outgoing_txns
        FROM subset
        GROUP BY from_address),
    t AS(SELECT DISTINCT to_address, count(*) as num_incoming_txns
        FROM subset
        GROUP BY to_address)
    SELECT COALESCE(from_address,to_address) as addr,
            COALESCE(num_outgoing_txns,0) as outgoing_txns,
            COALESCE(num_incoming_txns,0) as incoming_txns,
            maxnonce
    FROM f FULL JOIN t
    ON f.from_address = t.to_address)

SELECT *, (outgoing_txns + incoming_txns) as total_txns
FROM tot
ORDER BY total_txns desc
LIMIT 50

,addr,outgoing_txns,incoming_txns,maxnonce,total_txns
0,0xea674fdde714fd979de3edf0f56aa9716b898ec8,16425926,359,16425925.0,16426285
1,0x8d12a197cb00d4747a1fe03395095ce2a5cc6819,0,10520475,NaN,10520475
2,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,10164702,368,10164701.0,10165070
3,0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be,2762530,4642263,2762529.0,7404793
4,0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98,6814854,235407,6814853.0,7050261
5,0x829bd824b016326a401d083b33d092293333a830,6623903,4050,6623902.0,6627953
6,0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208,0,5159946,NaN,5159946
7,0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c,4608447,31,4608446.0,4608478
8,0x2a65aca4d5fc5b5c859090a6c34d164135398226,3906821,28,3906820.0,3906849
9,0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0,0,2954243,NaN,2954243
10,0x06012c8cf97bead5deae237070f9587f8e7a266d,0,2817530,NaN,2817530
11,0x32be343b94f860124dc4fee278fdcbd38c102d88,1310057,1084444,1310056.0,2394501
12,0x70faa28a6b8d6829a4b1e649d26ec9a2a39ba413,292961,1928329,292960.0,2221290
13,None,0,2109247,NaN,2109247
14,0xf230b790e05390fc8295f4d3f60332c93bed42e2,0,1979358,NaN,1979358
15,0xa7a7899d944fe658c4b0a1803bab2f490bd3849e,1957833,126,1957832.0,1957959
16,0xceceaa8edc0830c7cec497e33bb3a3c28dd55a32,1908247,258,1908246.0,1908505
17,0x209c4784ab1e8183cf58ca33cb740efbf3fc18ef,0,1740532,NaN,1740532
18,0x2b5634c42055806a59e9107ed44d43c426e58258,1241744,483626,1241743.0,1725370
19,0xb2930b35844a230f00e51431acae96fe543a0347,1597539,7798,1597538.0,1605337
20,0xe94b04a0fed112f3664e45adb2b8915693dd5ff3,0,1551056,NaN,1551056
21,0xa3c1e324ca1ce40db73ed6026c4a177f099b5770,0,1507229,NaN,1507229
22,0x6cace0528324a8afc2b157ceba3cdd2a27c4e21f,1500780,30,1500779.0,1500810
23,0x03df4c372a29376d2c8df33a1b5f001cd8d68b0e,0,1452721,NaN,1452721
24,0xd26114cd6ee289accf82350c8d8487fedb8a0c07,0,1395895,NaN,1395895
25,0xf5bec430576ff1b82e44ddb5a1c93f6f9d0884f3,260547,1099097,260546.0,1359644
26,0x6090a6e47849629b7245dfa1ca21d94cd15878ef,0,1277461,NaN,1277461
27,0xfa52274dd61e1643d2205169732f29114bc240b3,0,1251754,NaN,1251754
28,0x0d0707963952f2fba59dd06f2b425ace40b492fe,704444,492072,704443.0,1196516
29,0xd34da389374caad1a048fbdc4569aae33fd5a375,1150417,1085,1150416.0,1151502
30,0xd551234ae421e3bcba99a0da6d736074f22192ff,1104101,758,1104100.0,1104859
31,0x0681d8db095565fe8a346fa0277bffde9c0edbbf,1078176,727,1078175.0,1078903
32,0x876eabf441b2ee5b5b0554fd502a8e0600950cfa,523581,507223,523580.0,1030804
33,0x60d0cc2ae15859f69bf74dadb8ae3bd58434976b,266,1014108,265.0,1014374
34,0x564286362092d8e7936f0549571a803b203aaced,1011273,678,1011272.0,1011951
35,0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0,1010315,123,1010314.0,1010438
36,0x05ee546c1a62f90d7acbffd6d846c9c54c7cf94c,818089,184250,818088.0,1002339
37,0x390de26d772d2e2005c6d1d24afc902bae37a4bb,475136,522849,475135.0,997985
38,0x61c808d82a3ac53231750dadc13c777b59310bd9,993913,152,993912.0,994065
39,0x7ed1e469fcb3ee19c0366d829e291451be638e59,319537,603061,319536.0,922598
40,0xc179fbddc946694d11185d4e15dbba5fd0adac0a,222,895482,221.0,895704
41,0x236f9f97e0e62388479bf9e5ba4889e46b0273c3,661504,203126,661503.0,864630
42,0x1e9939daaad6924ad004c2560e90804164900341,860924,128,860923.0,861052
43,0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac,0,856720,NaN,856720
44,0xb1690c08e213a35ed9bab7b318de14420fb57d8c,0,854893,NaN,854893
45,0x69ea6b31ef305d6b99bb2d4c9d99456fa108b02a,478073,360209,478072.0,838282
46,0x74fd51a98a4a1ecbef8cc43be801cce630e260bd,0,825244,NaN,825244
47,0x91337a300e0361bddb2e377dd4e88ccb7796663d,100413,723465,100412.0,823878
48,0x93e682107d1e9defb0b5ee701c71707a4b2e46bc,0,817912,NaN,817912
49,0x6cc5f688a315f3dc28a7781717a9a798a59fda7b,499270,312401,499269.0,811671